import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HomeWrapper from '@/components/HomeWrapper'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '8meta ui/ux',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomeWrapper>
          {children}
        </HomeWrapper>
      </body>
    </html>
  )
}
